#
# Jekyll basic configurations
#

source:       ./_source
destination:  ./_site
exclude:      ['app.less']
timezone:     Asia/Hong_Kong
permalink:    /:categories/:title
markdown:     redcarpet
highlighter:  pygments

#
# Jekyll serve settings
#

port:         4321

#
# Jekyll build settings
#

future:       false
