# Jekyll configurations
source:       .
destination:  ./_site
permalink:    /:categories/:title
markdown:     rdiscount

# Jekyll server settings
auto:         true
server:       ture
server_port:  4321
exclude:
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- a.less

# Custom settings
domain:       sparanoid.com
url:          http://sparanoid.com
# file:         http://sparanoid.s3-website-us-east-1.amazonaws.com
# file:         http://d349cztnlupsuf.cloudfront.net
file:         http://rsrc.sparanoid.com
# file:         http://c1288.orca.io
css:          css
feed:         feed/
name:         Sparanoid
user:         Tunghiao Liu
email:        info@sparanoid.com
slogan:       I make things that don't suck.
twitter:      sparanoid
donate:       https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=VJRCEYRS8GTYE&lc=C2&item_name=Plugin%20Donation&button_subtype=services&currency_code=USD&bn=PP%2dBuyNowBF%3abtn_buynowCC_LG%2egif%3aNonHosted