# jekyll configurations
source:       .
destination:  ./_site
permalink:    /:categories/:title
markdown:     rdiscount

# jekyll server settings
auto:         true
server:       ture
server_port:  4321
exclude:      LICENSE, Rakefile, README.md

# custom settings
domain:       sparanoid.com
url:          http://sparanoid.com
# file:         http://rsrc.sparanoid.com
file:         http://d349cztnlupsuf.cloudfront.net
css:          css
feed:         feed/
name:         Sparanoid
user:         Tunghiao Liu
email:        info@sparanoid.com
slogan:       I make things that don't suck.
twitter:      sparanoid
donate:       https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=VJRCEYRS8GTYE&lc=C2&item_name=Plugin%20Donation&button_subtype=services&currency_code=USD&bn=PP%2dBuyNowBF%3abtn_buynowCC_LG%2egif%3aNonHosted