# Jekyll configurations
source:       ./_source
destination:  ./_site
plugins:      ./_plugins
markdown:     rdiscount
permalink:    /:categories/:title

# Jekyll server settings
auto:         true
server:       ture
server_port:  4321
exclude:
  - a.less

# Static images URL
file:         http://sparanoid.s3-website-us-east-1.amazonaws.com
# file:         http://d349cztnlupsuf.cloudfront.net
# file:         http://rsrc.sparanoid.com
# file:         http://c1288.orca.io

# Other custom settings
domain:       sparanoid.com
url:          http://sparanoid.com
css:          css
feed:         feed/
name:         Sparanoid
user:         Tunghiao Liu
email:        t@sparanoid.com
slogan:       I make things that don't suck.
twitter:      sparanoid
donate:       https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LTXZ835Y6T95S
availability: free