# Jekyll basic configurations
source:       ./_source
destination:  ./_site
exclude:      ['a.less']
timezone:     Asia/Hong_Kong
permalink:    /:categories/:title
markdown:     rdiscount

# Jekyll serve settings
port:         4321

# Jekyll build settings
future:       false

# Other custom settings
domain:       sparanoid.com
url:          http://sparanoid.com
file:         http://d349cztnlupsuf.cloudfront.net
css:          css
feed:         feed/
name:         Sparanoid
user:         Tunghiao Liu
email:        t@sparanoid.com
slogan:       I make things that don't suck.
twitter:      sparanoid
donate:       https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LTXZ835Y6T95S
availability: free