# jekyll configurations
source:       .
destination:  ./_site
permalink:    /:categories/:title
markdown:     rdiscount

# jekyll server settings
auto:         true
server:       ture
server_port:  4321
exclude:      LICENSE, Rakefile, README.md

# custom settings
url:          sparanoid.com
file:         http://rsrc.sparanoid.com
css:          css
feed:         feed/
name:         Sparanoid
user:         Tunghiao Liu
email:        info@sparanoid.com
slogan:       I make things that don't suck.
twitter:      sparanoid